from __future__ import annotations

import keyword
import re
from dataclasses import dataclass
from pathlib import Path

from .ast import TLConstructor, TLMethod, TLSchema


@dataclass(frozen=True, slots=True)
class GeneratedFiles:
    types_py: Path
    functions_py: Path
    registry_py: Path
    legacy_types_py: Path | None = None
    legacy_normalizers_py: Path | None = None


_RE_NON_IDENT = re.compile(r"[^0-9a-zA-Z_]+")

# Reviewed projections for historical fields whose wire contract cannot be
# inferred mechanically from a same-named current field. Keys are signed TL ids.
_LEGACY_FIELD_ADAPTERS: dict[tuple[str, int], dict[str, str]] = {
    ("poll", 1484026161): {  # poll#58747131
        "hash": "0",
    },
    ("pollAnswerVoters", 997055186): {  # pollAnswerVoters#3b6ddad2
        "flags": "(int(value.flags) & 3) | (1 << 2)",
        "voters": "value.voters",
        "recent_voters": "[]",
    },
}


def _snake(name: str) -> str:
    name = name.replace(".", "_")
    name = _RE_NON_IDENT.sub("_", name)
    name = re.sub(r"([a-z0-9])([A-Z])", r"\1_\2", name)
    name = re.sub(r"_+", "_", name).strip("_")
    return name.lower()


def _pascal(name: str) -> str:
    s = _snake(name)
    out = "".join(part[:1].upper() + part[1:] for part in s.split("_") if part)
    # Avoid invalid identifiers like `class True(...)` for TL constructors named `true`.
    if keyword.iskeyword(out):
        out = f"TL{out}"
    return out


def _safe_ident(name: str) -> str:
    name = _snake(name)
    if not name:
        name = "field"
    if name[0].isdigit():
        name = f"f_{name}"
    if keyword.iskeyword(name):
        name = f"{name}_"
    return name


def _header(*, any_type: bool = False) -> str:
    typing_import = "Any, ClassVar" if any_type else "ClassVar"
    return (
        "# This file is auto-generated. DO NOT EDIT.\n"
        "# Generated by tools/gen_tl.py\n"
        "from __future__ import annotations\n\n"
        "from dataclasses import dataclass\n"
        f"from typing import {typing_import}\n\n"
    )


def _render_constructor(
    cls: TLConstructor,
    *,
    py_name: str | None = None,
    inbound_only: bool = False,
    field_type: str = "object",
) -> tuple[str, str]:
    py_name = py_name or _pascal(cls.name)
    tl_id = cls.constructor_id if cls.constructor_id is not None else 0
    fields: list[tuple[str, str]] = []
    params_meta: list[tuple[str, str]] = []
    seen: set[str] = set()
    for p in cls.params:
        if getattr(p, "is_generic", False):
            continue
        fname = _safe_ident(p.name)
        if fname in seen:
            # very rare, but guard anyway
            i = 2
            while f"{fname}_{i}" in seen:
                i += 1
            fname = f"{fname}_{i}"
        seen.add(fname)
        fields.append((fname, field_type))
        params_meta.append((fname, p.type_ref.raw))

    lines: list[str] = [f"@dataclass(slots=True)\nclass {py_name}(TLObject):"]
    lines.append(f"    TL_ID: ClassVar[int] = {tl_id}")
    lines.append(f'    TL_NAME: ClassVar[str] = "{cls.name}"')
    if inbound_only:
        lines.append("    TL_INBOUND_ONLY: ClassVar[bool] = True")
    lines.append(f"    TL_PARAMS: ClassVar[tuple[tuple[str, str], ...]] = {tuple(params_meta)!r}")
    for fname, ftype in fields:
        lines.append(f"    {fname}: {ftype}")
    if not fields:
        lines.append("    pass")
    lines.append("")
    return py_name, "\n".join(lines)


def _render_method(m: TLMethod) -> tuple[str, str]:
    py_name = _pascal(m.name)
    tl_id = m.constructor_id if m.constructor_id is not None else 0
    fields: list[tuple[str, str]] = []
    params_meta: list[tuple[str, str]] = []
    seen: set[str] = set()
    for p in m.params:
        if getattr(p, "is_generic", False):
            continue
        fname = _safe_ident(p.name)
        if fname in seen:
            i = 2
            while f"{fname}_{i}" in seen:
                i += 1
            fname = f"{fname}_{i}"
        seen.add(fname)
        fields.append((fname, "object"))
        params_meta.append((fname, p.type_ref.raw))

    lines: list[str] = [f"@dataclass(slots=True)\nclass {py_name}(TLRequest):"]
    lines.append(f"    TL_ID: ClassVar[int] = {tl_id}")
    lines.append(f'    TL_NAME: ClassVar[str] = "{m.name}"')
    lines.append(f'    TL_RESULT: ClassVar[str] = "{m.result.raw}"')
    lines.append(f"    TL_PARAMS: ClassVar[tuple[tuple[str, str], ...]] = {tuple(params_meta)!r}")
    for fname, ftype in fields:
        lines.append(f"    {fname}: {ftype}")
    if not fields:
        lines.append("    pass")
    lines.append("")
    return py_name, "\n".join(lines)


def _legacy_python_name(constructor: TLConstructor) -> str:
    if constructor.constructor_id is None:
        raise ValueError(f"Legacy constructor {constructor.name!r} has no wire id")
    return f"_Legacy{_pascal(constructor.name)}{constructor.constructor_id & 0xFFFFFFFF:08X}"


def _params_by_name(constructor: TLConstructor) -> dict[str, str]:
    return {
        _safe_ident(param.name): param.type_ref.raw
        for param in constructor.params
        if not getattr(param, "is_generic", False)
    }


def _flag_mask(constructor: TLConstructor, flag_name: str) -> int:
    mask = 0
    for param in constructor.params:
        type_expr = param.type_ref.raw
        if "?" not in type_expr:
            continue
        prefix = type_expr.split("?", 1)[0]
        if "." not in prefix:
            continue
        owner, bit_text = prefix.split(".", 1)
        if _safe_ident(owner) != flag_name:
            continue
        try:
            mask |= 1 << int(bit_text)
        except ValueError:
            continue
    return mask


def _render_legacy_normalizer(
    legacy: TLConstructor,
    current: TLConstructor,
) -> tuple[str, str]:
    if legacy.constructor_id is None:
        raise ValueError(f"Legacy constructor {legacy.name!r} has no wire id")
    legacy_params = _params_by_name(legacy)
    current_params = _params_by_name(current)
    adapters = _LEGACY_FIELD_ADAPTERS.get((legacy.name, legacy.constructor_id), {})
    function_name = f"_normalize_{legacy.constructor_id & 0xFFFFFFFF:08x}"
    target_name = _pascal(current.name)
    source_name = _legacy_python_name(legacy)
    lines = [f"def {function_name}(value: {source_name}) -> {target_name}:"]
    lines.append(f"    return {target_name}(")
    for field, current_type in current_params.items():
        adapter = adapters.get(field)
        if adapter is not None:
            lines.append(f"        {field}={adapter},")
            continue
        legacy_type = legacy_params.get(field)
        if legacy_type is not None:
            if legacy_type != current_type:
                raise ValueError(
                    "Legacy normalizer requires a reviewed adapter for "
                    f"{legacy.name}.{field}: {legacy_type!r} -> {current_type!r}"
                )
            if current_type == "#":
                mask = _flag_mask(legacy, field)
                lines.append(f"        {field}=int(value.{field}) & {mask},")
            else:
                lines.append(f"        {field}=value.{field},")
            continue

        if current_type == "#":
            lines.append(f"        {field}=0,")
            continue
        if "?" in current_type and "." in current_type.split("?", 1)[0]:
            inner = current_type.split("?", 1)[1]
            lines.append(f"        {field}={'False' if inner == 'true' else 'None'},")
            continue
        raise ValueError(
            "Legacy normalizer cannot synthesize required field "
            f"{current.name}.{field} ({current_type})"
        )
    lines.append("    )")
    lines.append("")
    return function_name, "\n".join(lines)


def generate(
    schema: TLSchema,
    out_dir: Path,
    *,
    legacy_schema: TLSchema | None = None,
) -> GeneratedFiles:
    """
    Generate public schema modules plus private inbound-compatibility modules.
    """

    out_dir.mkdir(parents=True, exist_ok=True)
    types_py = out_dir / "types.py"
    functions_py = out_dir / "functions.py"
    registry_py = out_dir / "registry.py"
    legacy_types_py = out_dir / "_legacy_types.py"
    legacy_normalizers_py = out_dir / "_legacy_normalizers.py"

    legacy_constructors = tuple(legacy_schema.constructors) if legacy_schema else ()
    if legacy_schema and legacy_schema.methods:
        raise ValueError("Legacy compatibility schemas may contain constructors only")

    public_names = [constructor.name for constructor in schema.constructors]
    if len(set(public_names)) != len(public_names):
        raise ValueError(
            "Current schema contains duplicate TL constructor names; historical layouts "
            "must be passed through legacy_schema"
        )
    public_method_names = [method.name for method in schema.methods]
    if len(set(public_method_names)) != len(public_method_names):
        raise ValueError("Current schema contains duplicate TL method names")

    public_ids = {
        constructor.constructor_id
        for constructor in schema.constructors
        if constructor.constructor_id is not None
    }
    seen_legacy_ids: set[int] = set()
    for constructor in legacy_constructors:
        constructor_id = constructor.constructor_id
        if constructor_id is None:
            raise ValueError(f"Legacy constructor {constructor.name!r} has no wire id")
        if constructor_id in public_ids or constructor_id in seen_legacy_ids:
            raise ValueError(f"Duplicate inbound constructor id: {constructor_id}")
        seen_legacy_ids.add(constructor_id)

    # Types
    type_chunks: list[str] = [_header(), "from telecraft.tl.runtime import TLObject\n\n"]
    type_names: list[str] = []
    for c in schema.constructors:
        name, chunk = _render_constructor(c)
        type_names.append(name)
        type_chunks.append(chunk)
    type_chunks.append(f"__all__ = {type_names!r}\n")
    types_py.write_text("".join(type_chunks), encoding="utf-8", newline="\n")

    # Functions
    fn_chunks: list[str] = [_header(), "from telecraft.tl.runtime import TLRequest\n\n"]
    fn_names: list[str] = []
    for m in schema.methods:
        name, chunk = _render_method(m)
        fn_names.append(name)
        fn_chunks.append(chunk)
    fn_chunks.append(f"__all__ = {fn_names!r}\n")
    functions_py.write_text("".join(fn_chunks), encoding="utf-8", newline="\n")

    # Historical wire layouts are deliberately private and inbound-only.  They
    # are decoded through the inbound registry and normalized before TLReader
    # returns, so callers only ever see current public generated classes.
    legacy_type_chunks: list[str] = [
        _header(any_type=True),
        "from telecraft.tl.runtime import TLObject\n\n",
    ]
    legacy_names: list[str] = []
    for constructor in legacy_constructors:
        private_name = _legacy_python_name(constructor)
        _name, chunk = _render_constructor(
            constructor,
            py_name=private_name,
            inbound_only=True,
            field_type="Any",
        )
        legacy_names.append(private_name)
        legacy_type_chunks.append(chunk)
    legacy_type_chunks.append("__all__: list[str] = []\n")
    legacy_types_py.write_text("".join(legacy_type_chunks), encoding="utf-8", newline="\n")

    current_by_name = {constructor.name: constructor for constructor in schema.constructors}
    normalizer_chunks: list[str] = [
        "# This file is auto-generated. DO NOT EDIT.\n",
        "# Generated by tools/gen_tl.py\n",
        "from __future__ import annotations\n\n",
        "from ._legacy_types import (\n",
    ]
    for name in legacy_names:
        normalizer_chunks.append(f"    {name},\n")
    normalizer_chunks.extend([")\n", "from .types import (\n"])
    target_names: list[str] = []
    for constructor in legacy_constructors:
        current = current_by_name.get(constructor.name)
        if current is None:
            raise ValueError(
                f"No current constructor named {constructor.name!r} for legacy normalization"
            )
        target_name = _pascal(current.name)
        if target_name not in target_names:
            target_names.append(target_name)
            normalizer_chunks.append(f"    {target_name},\n")
    normalizer_chunks.extend([")\n\n"])
    normalizer_names: list[tuple[int, str]] = []
    for constructor in legacy_constructors:
        current = current_by_name[constructor.name]
        function_name, chunk = _render_legacy_normalizer(constructor, current)
        constructor_id = constructor.constructor_id
        if constructor_id is None:  # validated above; keeps the invariant local and typed
            raise ValueError(f"Legacy constructor {constructor.name!r} has no wire id")
        normalizer_names.append((constructor_id, function_name))
        normalizer_chunks.append(chunk)
    normalizer_chunks.append("LEGACY_NORMALIZERS_BY_ID = {\n")
    for constructor_id, function_name in normalizer_names:
        normalizer_chunks.append(f"    {constructor_id}: {function_name},\n")
    normalizer_chunks.append("}\n")
    legacy_normalizers_py.write_text("".join(normalizer_chunks), encoding="utf-8", newline="\n")

    # Registry (constructor_id -> class)
    reg_lines: list[str] = [
        _header(),
        "from typing import Type\n\n",
        "from .types import *  # noqa: F403\n",
        "from .functions import *  # noqa: F403\n\n",
        "from ._legacy_types import (\n",
    ]
    for name in legacy_names:
        reg_lines.append(f"    {name},\n")
    reg_lines.extend(
        [
            ")\n\n",
            "TLObjectType = Type[object]\n\n",
            "CONSTRUCTORS_BY_ID: dict[int, TLObjectType] = {\n",
        ]
    )

    for c in schema.constructors:
        if c.constructor_id is None:
            continue
        reg_lines.append(f"    {c.constructor_id}: {_pascal(c.name)},\n")
    reg_lines.append("}\n\nLEGACY_CONSTRUCTORS_BY_ID: dict[int, TLObjectType] = {\n")
    for constructor in legacy_constructors:
        reg_lines.append(f"    {constructor.constructor_id}: {_legacy_python_name(constructor)},\n")
    reg_lines.append("}\n\nINBOUND_CONSTRUCTORS_BY_ID: dict[int, TLObjectType] = {\n")
    reg_lines.append("    **CONSTRUCTORS_BY_ID,\n")
    reg_lines.append("    **LEGACY_CONSTRUCTORS_BY_ID,\n")
    reg_lines.append("}\n\nMETHODS_BY_ID: dict[int, TLObjectType] = {\n")
    for m in schema.methods:
        if m.constructor_id is None:
            continue
        reg_lines.append(f"    {m.constructor_id}: {_pascal(m.name)},\n")
    reg_lines.append("}\n")
    registry_py.write_text("".join(reg_lines), encoding="utf-8", newline="\n")

    return GeneratedFiles(
        types_py=types_py,
        functions_py=functions_py,
        registry_py=registry_py,
        legacy_types_py=legacy_types_py,
        legacy_normalizers_py=legacy_normalizers_py,
    )
